### PR TITLE
V2 API Route

### PR DESCRIPTION
**Pull request by PhlexPlexico**
This is going to be a bit of a longer WIP branch, but this has some sweeping changes that should make this compatible with the latest versions of get5. If there is an older version, it will still look for the G5WS plugin, however it is now no longer required as of Get5 0.14.

This is the feature list that needs to be incorporated for the API that holds the connection to the game server:
## Series Flow
- [X] Veto
  - [X]  Map Veto
  - [X] Map Pick
  - [X] Side Pick
- [X] OnMapResult
- [X] OnSeriesResult
- [x] OnBackupRestore (for remote backups)
## Map Flow
- [x] OnGoingLive (update map stat info on the API side).
- [x] OnMatchPaused
- [x] OnMatchUnpaused
- [x] OnPlayerDeath (the new stats update will reside here)
~~- [ ] OnPlayerBecameMVP~~
- [x] OnRoundEnd
- [x] OnBombPlanted
- [x] OnBombDefused

## Misc
- [x] Documentation
- [x] Cleanup of duplicate functionality
- [x] Docker build/tagging
- [x] Dockerfile cleanup to ensure it can still actually launch within a docker conatiner
- [x] Remote Backups
- [x] Remote Demo Uploads

There is still a few other changes that need to be made, such as extending new features for match configs (like more refined veto selection and choices) that *may* make it into this PR, but it is still undecided. 

This update will also attempt to start converting some of this project into TypeScript, as there has been quite a few issues I've ran into with typing.

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
Can confirm basic match creation is working as intended while making older versions still compatible with the old G5WS plugin.

**Comment by PhlexPlexico** [comment]
And also https://phlex.avidgamers.me is now pointing to the new instance. So if anyone out there wants to test, that is available!

**Comment by PhlexPlexico** [comment]
One or two possible issues that may have to be rectified after review and initial testing

- Team Logos not transferring over, need to do this on series init somehow. However, team logos were already fairly broken to begin with.
- backups and demos may not save in the public folder, but under src/public. Will need to verify that this isn't the case.

**Comment by PhlexPlexico** [comment]
I think aside from team logos, this should be good to merge now. Even without team logos, this is now working as intended I believe.

**Comment by Bunker56** [comment]
Get5 0.14.7 (default cfg)
[get5.smx] Event HTTP request failed due to a network or configuration error. Make sure you have enclosed your event URL in quotes.
do I need additional plugin settings or did I fail to see something?

**Comment by Bunker56** [comment]
Sorry!/ I will unsubscribe in more detail later, while there is no possibility...

**Comment by PhlexPlexico** [comment]
So did you figure it out? You could also check the API logs and see if there's any error on its end.

**Comment by Bunker56** [comment]
one more thing confuses me, there is a _**get5_remote_log_url**_ parameter in the plugin documentation, but it is not in the config file. Could it be the case?

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/G5API/blob/c92bfb71476a89be0085b61fb13a08455b6fd371/src/utility/serverrcon.js#L208

See here, it's set during the match setup, as well as a handful of other url settings for get5. The config file does not set these as they need to be set via rcon.

**Comment by PhlexPlexico** [comment]
And please, if you need any more questions answered, feel free to create a new Discussion :)

**Comment by Bunker56** [comment]
this is a piece of the log with an error that was in the previous API, the API logs are fine, there are no errors
BNK#3: !r
L 06/24/2023 - 18:27:12: "BNK#3<3><STEAM_1:1:537158178><TERRORIST>" say "!r"
_**src/common/httpclient.cpp (808) : pHost && *pHost**_
src/common/httpclient.cpp (808) : pHost && *pHost
L 06/24/2023 - 18:27:12: [get5.smx] Event HTTP request failed due to a network or configuration error. Make sure you have enclosed your event URL in quotes.
BNK#1: !r
L 06/24/2023 - 18:27:26: "BNK#1<6><STEAM_1:1:537225542><CT>" say "!r"
_**src/common/httpclient.cpp (808) : pHost && *pHost**_
src/common/httpclient.cpp (808) : pHost && *pHost
L 06/24/2023 - 18:27:26: [get5.smx] Event HTTP request failed due to a network or configuration error. Make sure you have enclosed your event URL in quotes.

**Comment by Bunker56** [comment]
I don't understand how and where to catch her...

**Pull request merged**
