### PR TITLE
Adding ghcr automatic builds of containers

### PR DESCRIPTION
**Pull request by kubo6472**
This still needs to be tested a lot. But it may be a solution for having the G5API docker container updated automatically everytime there is a commit.

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
And is this is specifically for Github repo? I assume it's the same as docker hub? Could take a look into it, but I was actually planning on using DockerHub.

**Comment by PhlexPlexico** [comment]
Actually thinking more about this, would it at all be possible to publish to Docker Hub instead? I was going to try my hand at with making a compose script that will take phlex/G5API:latest and phlex/g5v on dockerhub and build the entire system, reverse proxy and all.

**Comment by kubo6472** [comment]
> 
> 
> Actually thinking more about this, would it at all be possible to publish to Docker Hub instead? I was going to try my hand at with making a compose script that will take phlex/G5API:latest and phlex/g5v on dockerhub and build the entire system, reverse proxy and all.

Tmk docker hub removed the github sync feature from free plans. I think of this as a viable replacement. Next item on the list is a docker-compose file, so I assume that is the best fit to bring on the entire stack.

**Comment by PhlexPlexico** [comment]
Hmm, honestly I'm neither here nor there about it. Considering I just made a docker compose for a complete system setup, I'm not exactly against having the package just on GHCR... However, I just need to know if it will eventually cost anything, is all! If there's no cost, I can even update the docker container to use the package that would be hosted here!

**Comment by kubo6472** [comment]
Everything is free*
*-https://github.com/features/packages#pricing

**Comment by kubo6472** [comment]
I will try & fix the caddy stuff, because I still can not get over how easy you can have HTTPS using that.

**Pull request closed without merging**
