### PR TITLE
Refactor Database Calls

### PR DESCRIPTION
**Pull request by PhlexPlexico**
Since pools don't really support transactions I've been running into issues with connections closing early. There should be another approach to this (releasing specific connections) that I would like to look into one day, but for now I think this should be no problem for inserting data I believe. So this should fix any connection issues that cause crashing in the environment when there is too much traffic to the server.

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
Tested playing a BO3 and it seems that everything seems to be working just fine. Going to merge this in next month here and maybe create a new release.

**Comment by PhlexPlexico** [comment]
@kdev please review :) I believe these should all be correct now.

**Comment by kdev** [comment]
> @kdev please review :) I believe these should all be correct now.

I'm still not amazed by the code style but you changed what I suggested so that lgtm!

**Comment by PhlexPlexico** [comment]
If you ever wanna take a stab at the entire codebase to update feel free to let me know and I can make changes as well as needed! Always open to a more consistent format.

**Comment by kdev** [comment]
> If you ever wanna take a stab at the entire codebase to update feel free to let me know and I can make changes as well as needed! Always open to a more consistent format.

I'll take a look at it when I have some spare time, but for now this looks good

**Review by kdev — APPROVED** [review]

**Pull request merged**
