### PR TITLE
Fix ports, g5api now actually runs on 3301

### PR DESCRIPTION
**Pull request by kubo6472**
This got me down a rabbit hole on why the matches stopped being ended on panel and I stopped receiving any kind of stats. It was because the g5api wasn't able to be contacted by the game server.

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
Uhh I'm not sure if this is the solution to your problem. You should be using the bundled reverse proxy in order to hit the API, you should never be hitting it directly, imo. Hence why it's not exposed. If you want to make that change, you can make it locally but this docker compose file is to let brand new users setup the entire stack in one go, not just pieces of it :)

I hope that makes sense, if it doesn't please lemme know!

**Comment by kubo6472** [comment]
Oh wait, yeah, this does not help me at all. The api is still inaccesible. Why have I not noticed this.

**Comment by kubo6472** [comment]
> Uhh I'm not sure if this is the solution to your problem. You should be using the bundled reverse proxy in order to hit the API, you should never be hitting it directly, imo. Hence why it's not exposed. If you want to make that change, you can make it locally but this docker compose file is to let brand new users setup the entire stack in one go, not just pieces of it :)
> 
> I hope that makes sense, if it doesn't please lemme know!

Yeah it does, but for some reason the matches aren't ending or any stats being sent. I just rebuilt the stack. Gotta test some, will let you know if it works now.

**Comment by kubo6472** [comment]
https://gist.github.com/kubo6472/ec1ef505a95fd4c5d1c931332e39b5f8
gameserver logs
https://gist.github.com/kubo6472/34ae770f736a24fb8f0b86e73a44afcb
caddy logs

**Comment by kubo6472** [comment]
I am going to redeploy the docker-compose elsewhere entirely, since this vps has a closed-first firewall. Its being used as in the repo. no edits

**Comment by PhlexPlexico** [comment]
It should be something like this, you can strip the prefix - 

```
route /api/* {
         uri strip_prefix /api
         reverse_proxy http://172.18.0.4:3301
 }
```

That uri strip_prefix should work and fix any issues regarding that.

**Comment by kubo6472** [comment]
yea, I see. I am just trying to eliminate variables from how I had it set up before migrating to this config. maybe I am just missing a port. no idea at this point.

**Comment by kubo6472** [comment]
image
tried completely other domain. still doesnt work. will debug further, or move to the public panel.

**Comment by kubo6472** [comment]
image

**Comment by kubo6472** [comment]
image
I have no idea what this means. something something, it cant reach the api on port 3301

**Comment by kubo6472** [comment]
I have the same problem with phlex.avidgamers, and a panel, that hasn't been updated for months, where it started happening randomly, too. https://phlex.avidgamers.me/match/966

**Comment by PhlexPlexico** [comment]
Which plugin are you currently using to record stats? I just used this the other day to test Get5 0.9 and it was working as intended. Is there any logs you can get from either the API or front end containers? The only error I can see is this - 

```log
Error on isAvailable server: SyntaxError: Unexpected token { in JSON at position 65
0|G5API    | SyntaxError: Unexpected token { in JSON at position 65
0|G5API    |     at JSON.parse (<anonymous>)
0|G5API    |     at ServerRcon.isGet5Available (file:///G5API/utility/serverrcon.js:61:39)
0|G5API    |     at runMicrotasks (<anonymous>)
0|G5API    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|G5API    |     at async file:///G5API/routes/matches/matches.js:736:10
```

Which is telling me that the gameserver may be sending some unexpected values.

**Comment by kubo6472** [comment]
> Which plugin are you currently using to record stats? I just used this the other day to test Get5 0.9 and it was working as intended. Is there any logs you can get from either the API or front end containers? The only error I can see is this -
> 
> ```
> Error on isAvailable server: SyntaxError: Unexpected token { in JSON at position 65
> 0|G5API    | SyntaxError: Unexpected token { in JSON at position 65
> 0|G5API    |     at JSON.parse (<anonymous>)
> 0|G5API    |     at ServerRcon.isGet5Available (file:///G5API/utility/serverrcon.js:61:39)
> 0|G5API    |     at runMicrotasks (<anonymous>)
> 0|G5API    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 0|G5API    |     at async file:///G5API/routes/matches/matches.js:736:10
> ```
> 
> Which is telling me that the gameserver may be sending some unexpected values.

I am using [this](https://github.com/PhlexPlexico/G5WS/releases/download/Nightly-d43b0c/G5WS.zip) and [this](https://ci.splewis.net/job/get5/lastSuccessfulBuild/artifact/builds/get5/get5-543.zip) as of now. I thought I would try 0.9 and the plugin I asked for in the discord server a while back, but haven't managed to get to it yet. Just trying to make this work.

**Comment by PhlexPlexico** [comment]
And what are the usual outputs from `get5_debug 32`? That error may be a red herring as my error logs may be out of date.

That being said, can you try a different server then? Try using dathost with the plugins and see if you're still running into errors. This sounds like a possibility of a firewall or network config not working on the gameserver, which I can not support.

**Comment by kubo6472** [comment]
> And what are the usual outputs from `get5_debug 32`? That error may be a red herring as my error logs may be out of date.
> 
> That being said, can you try a different server then? Try using dathost with the plugins and see if you're still running into errors. This sounds like a possibility of a firewall or network config not working on the gameserver (considering you've tried multiple APIs and panels... It's pointing more towards a gameserver issue, and not an API issue), which I can not support.

I will try debug 32, I tried debug 1 the only difference it seems that debug 1 logs stuff into console instead. I tried debug 16, too. The problem is right now. That I have a server, the same server I always had on the same host, with the same plugins & config. And for once even the same panel on one instance. I was in between seasons in leagues and suddenly when I moved my main panel from this old laptop @ home to a VPS it stops working everywhere. As I observe, the latest matches on your panel aren't ending, too.

**Comment by kubo6472** [comment]
Cant do dathost now, since it used to not ask for payment details outright, now it does. Nvm. I will ask my host and try it on some other host servers' I might get my hands on.

**Comment by kubo6472** [comment]
image

**Comment by PhlexPlexico** [comment]
Is there any reason why you're trying out the new login information things? If there's errors with that, please report them in a bug. From my testing I didn't run into any issues in regards to registering/logging in.

**Comment by kubo6472** [comment]
I am not trying to try out any new login info things. I have no idea what that is. I have some new logs. https://gist.github.com/kubo6472/400b13c5606f53af31bc0dbff6b5a38c

**Comment by PhlexPlexico** [comment]
I would hazard a guess someone is trying to login with the new feature then, so I would disregard that. I'm just testing the older version of get5 right now, but it seems that 0.9 plus the latest build from the other branch has everything working as intended https://phlex.avidgamers.me/match/967

**Comment by kubo6472** [comment]
> I would hazard a guess someone is trying to login with the new feature then, so I would disregard that. I'm just testing the older version of get5 right now, but it seems that 0.9 plus the latest build from the other branch has everything working as intended https://phlex.avidgamers.me/match/967

can you please attach here the latest g5ws build? I will test it out. just swapped the plugins again, still version for version, just to test for dumb anomalies. thx

**Comment by PhlexPlexico** [comment]
I downloaded the version you just linked earlier, same with get5, and everything is working.

**Comment by kubo6472** [comment]
correct me if im wrong please. but if the caddy reverse proxy is routing traffic for the api, the port 3301 is closed in the firewall (tried opening it already) and NOT exposed in the docker container (the compose expose flag seems funky, since I don't see any port open, my tactic of doing -ports 3301:3301 doesn't help either, bcs the reverse proxy's there.)

**Comment by kubo6472** [comment]
[G5WS.zip](https://github.com/PhlexPlexico/G5API/files/8164853/G5WS.zip)
I have this (zipped) smx from the splewis discord, is it still the most recent g5ws?

**Comment by PhlexPlexico** [comment]
> correct me if im wrong please. but if the caddy reverse proxy is routing traffic for the api, the port 3301 is closed in the firewall (tried opening it already) and NOT exposed in the docker container (the compose expose flag seems funky, since I don't see any port open, my tactic of doing -ports 3301:3301 doesn't help either, bcs the reverse proxy's there.)

The Caddy reverse proxy should be open to the world. Hence why it uses ports. Ports will bind the internal docker IP port to the external machine. 

The reason we use ports is we wish to expose it to the outside world. Technically, since you've defined port 3301 to be used in the API, it is exposed publically. Expose only exposes to other services, and not to the outside world. So right now, in the default install from the docker-compose file, we are exposing ports 80, 443 (for SSL), and 3301 to the outside world. It's up to your firewall to allow any connections to it. So that isn't the problem. Does https://csgo.bluenation.studio/api/matches work in a web browser? If so, the redirection provided by Caddy is working as intended, and everything on the API side is working as it should.


> [G5WS.zip](https://github.com/PhlexPlexico/G5API/files/8164853/G5WS.zip) I have this (zipped) smx from the splewis discord, is it still the most recent g5ws?

I believe that would have been the 0.9 installation which has different events. If you used that with the old version of get5, you're going to have a bad time. I just grabbed the latest nightly that is drafted as a pre-release for G5WS, and your link [here](https://ci.splewis.net/job/get5/lastSuccessfulBuild/artifact/builds/get5/get5-543.zip) for get5. Everything is working as intended, as you can see [here](https://phlex.avidgamers.me/match/970). I even updated the web panel to be the latest version to be in-line with what is in the master branch of the repo. As I said, this is most likely a networking issue where you may not be allowing out/in certain connections. It very well could be an issue if you're using a Windows machine to host these servers. I'm not sure where your problem lies, but everything here seems to be working as it should.

I hazard distributing builds across platforms as it gets cumbersome to tell you which the "right" one is. If you wish to test 0.9, you will have to compile it yourself from the branch as well.

**Comment by kubo6472** [comment]
Hey, many thanks for your time on this. I blame this now 100% to either some misconfiguration on my side on the server. Some host problems, and or some dep. plugins and extensions, and or sm/mm itself being outdated. Will handle this tmrw. https://phlex.avidgamers.me/match/971 does not work on your panel with exactly the configuration you specified. I am sorry for wasting so much of your time on this, I just thought I had it. Good night :)

**Comment by kubo6472** [comment]
https://phlex.avidgamers.me/match/973 I reinstalled the server and uploaded just brand new plugins & deps. It works. Hooray. I assume the error lied somewhere in the plugins. Got 30 servers tho. This is going to be a lengthy repair.

**Comment by PhlexPlexico** [comment]
Glad to hear it's working again :)

**Comment by kubo6472** [comment]
Okay, won't be introducing any new variables into the mix and I am moving to use your public panel for the time being. Thanks for providing such a service btw.

**Comment by kubo6472** [comment]
I seriously don't want to bother you with this, but just saying that it stopped working again. Even on public, and also on my own. I have no idea why is it happening, but since the matches already started, I can't do very much.

**Comment by PhlexPlexico** [comment]
I have zero clue, as it has nothing to do with the API (as I've tested it with several matches). It has to be the networking setup between your game servers and everything else, and I am unable to assist with that.

**Comment by kubo6472** [comment]
Again my mysterious problem with pm2 returns.
image

**Comment by kubo6472** [comment]
image
the errors in addresses were resolved moments later, b4 creating any matches, since I had some tab or whitespace there... the others, no idea...

**Comment by kubo6472** [comment]
There are currently 21 players online across two servers. The matches start, but don't report back a shiss. It worked, right after I nuked the config. Then I just added the four must have plugins: G5WS, get5, Warmup Fix & No Models + their respective deps. I theoretically can try nuking the stuff one-by-one, but it worked with the latest get5 build, and now It's borked. I am considering downgrading to the latest release of get5, which is 0.7.2 and wait for 0.9. But it still doesn't make any sense. Why it would work one time, then frik up another...

**Comment by PhlexPlexico** [comment]
If the getaddrinfo is failing, that would mean either the web server is unable to find the address beta.fakaheda.eu. This is most likely due to the server being unreachable. I just tried pinging this game server and all I'm getting are constant timeouts. If it's a local-only server, I would recommend either changing your host settings on the API server, or just using the direct IP instead. This is just sounding like a bad network setup, or a network that can't get in touch with the outside world.

**Comment by kubo6472** [comment]
> If the getaddrinfo is failing, that would mean either the web server is unable to find the address beta.fakaheda.eu. This is most likely due to the server being unreachable. I just tried pinging this game server and all I'm getting are constant timeouts. If it's a local-only server, I would recommend either changing your host settings on the API server, or just using the direct IP instead. This is just sounding like a bad network setup, or a network that can't get in touch with the outside world.

It's the same host it always was for the last two years. Just got in touch with them. I will try resolving all the hostnames to IPs. I would love to see if that would've fixed it. I am moving between public and my own, since I import all the teams and players from a CSV directly into the DB, doubt that's the issue, since I used public for a bit recently, too.

**Comment by PhlexPlexico** [comment]
I mean, nothing like that should matter. If I'm unbale to even ping the IP with it timing out, it would have to be whatever the connection is to the outside world. Especially if it's inconsistent. I would try using a different host for your CS:GO servers, as that may be the issue.

**Comment by kubo6472** [comment]
image
oh shoot 😄  so basically the story is that I need to debug if it is host based, or not. Will try that tmrw and let you know. thanks for everything. btw. please let me know, if you've received my 2 ko-fies.

**Comment by PhlexPlexico** [comment]
> image oh shoot 😄 so basically the story is that I need to debug if it is host based, or not. Will try that tmrw and let you know. thanks for everything. btw. please let me know, if you've received my 2 ko-fies.

Hah, it's no worries. Sometimes this is just the easiest way of communicating. But yes, I'm unable to reproduce and I was having some troubles even reaching your host/IP for the game server as well, which would be the main reason as to why nothing else can reach it. Could be a firewall issue on the game server where it's allowing game traffic (27015 TCP UDP) but no RCON access. 

And thank you very much! It's definitely not required for the help or anything, but it is highly appreciated!! 😄

**Comment by kubo6472** [comment]
and indeed, they were experiencing heavy DDOS attacks lately. seemingly no effect on servers themselves, but network infrastructure got simply overloaded. I will be investigating this further once I will deploy a server on my homelab thru srcds directly. I tipped simply bc. I asked for so much features and basically all of them got implemented. I am grateful, since you're saving me a lot of time and headache 😅 😄 

> (27015 TCP UDP) but no RCON access

Oh, then I'm definitely sure that's not me, since I have no servers on the default port.

**Comment by PhlexPlexico** [comment]
Anytime! I'm just glad people are using my tools :)

And sorry, I just default to 27105, but apparently the RCON port will be whatever you set the port to on CS! So as long as those ports are open (both TCP and UDP) there should be connections. But yeah, if there was mitigations put into effect for DDoS preventions, that may be the case as to why it's being blocked.

**Comment by kubo6472** [comment]
> That being said, can you try a different server then? Try using dathost with the plugins and see if you're still running into errors.

Heh, since then invested into dathost and it works flawlessly. Just getting a bit expensive, but it's worth it for me at least.

**Pull request closed without merging**
